--------------------------------------------------------
--  파일이 생성됨 - 일요일-12월-14-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISPATCH
--------------------------------------------------------

  CREATE TABLE "C##DPEM"."DISPATCH" 
   (	"DISPATCH_ID" VARCHAR2(20 BYTE), 
	"ORDER_ID" VARCHAR2(20 BYTE), 
	"DRIVER_ID" VARCHAR2(20 BYTE), 
	"CAR_NUM" VARCHAR2(20 BYTE), 
	"MATCHED_AT" DATE, 
	"ARRIVAL_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_SHEET
--------------------------------------------------------

  CREATE TABLE "C##DPEM"."ORDER_SHEET" 
   (	"ORDER_ID" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"ORIGIN" VARCHAR2(100 BYTE), 
	"DEST" VARCHAR2(100 BYTE), 
	"CARGO_INFO" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"PICKUP_TIME" DATE, 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT '대기'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPACE_STATUS
--------------------------------------------------------

  CREATE TABLE "C##DPEM"."SPACE_STATUS" 
   (	"CAR_NUM" VARCHAR2(20 BYTE), 
	"CURRENT_CAPA" NUMBER, 
	"RETURN_DEST" VARCHAR2(20 BYTE), 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##DPEM"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"USER_TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VEHICLE
--------------------------------------------------------

  CREATE TABLE "C##DPEM"."VEHICLE" 
   (	"CAR_NUM" VARCHAR2(20 BYTE), 
	"CAR_TYPE" VARCHAR2(20 BYTE), 
	"MAX_WEIGHT" NUMBER, 
	"DRIVER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View 업체별제품수
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##DPEM"."업체별제품수" ("제조업체", "제품수") AS 
  select 제조업체, count(*) from 제품
                                group by 제조업체
                                with check option
;
--------------------------------------------------------
--  DDL for View 우수고객
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##DPEM"."우수고객" ("고객아이디", "고객이름", "나이", "등급") AS 
  select 고객아이디, 고객이름, 나이, 등급 from 고객
                                    where 등급 ='vip'
                                    
                                    with check option
;
--------------------------------------------------------
--  DDL for View 제품1
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##DPEM"."제품1" ("제품번호", "제품명", "재고량", "제조업체") AS 
  SELECT 제품번호, 제품명, 재고량, 제조업체 FROM 제품
WITH CHECK OPTION
;
--------------------------------------------------------
--  DDL for View 제품2
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##DPEM"."제품2" ("제품번호", "재고량", "제조업체") AS 
  SELECT 제품번호, 재고량, 제조업체 FROM 제품
WITH CHECK OPTION
;
REM INSERTING into C##DPEM.DISPATCH
SET DEFINE OFF;
Insert into C##DPEM.DISPATCH (DISPATCH_ID,ORDER_ID,DRIVER_ID,CAR_NUM,MATCHED_AT,ARRIVAL_TIME) values ('20251214-0001','20251214-0001','dpem1234','28소8237',to_date('25/12/14','RR/MM/DD'),null);
REM INSERTING into C##DPEM.ORDER_SHEET
SET DEFINE OFF;
Insert into C##DPEM.ORDER_SHEET (ORDER_ID,USER_ID,ORIGIN,DEST,CARGO_INFO,PRICE,PICKUP_TIME,STATUS) values ('20251214-0001','dpem0117','서울이태원역','경기도의정부시가능동','침대 (50kg)',50000,to_date('25/12/15','RR/MM/DD'),'배차');
Insert into C##DPEM.ORDER_SHEET (ORDER_ID,USER_ID,ORIGIN,DEST,CARGO_INFO,PRICE,PICKUP_TIME,STATUS) values ('20251214-0002','dpem0117','1','1','1 (1kg)',1,to_date('25/12/25','RR/MM/DD'),'대기');
REM INSERTING into C##DPEM.SPACE_STATUS
SET DEFINE OFF;
REM INSERTING into C##DPEM.USERS
SET DEFINE OFF;
Insert into C##DPEM.USERS (USER_ID,PASSWORD,USER_NAME,PHONE,USER_TYPE) values ('김재영','1234','김재영','01022446702','고객');
Insert into C##DPEM.USERS (USER_ID,PASSWORD,USER_NAME,PHONE,USER_TYPE) values ('dpem0117','1234','김재영','01022446702','고객');
Insert into C##DPEM.USERS (USER_ID,PASSWORD,USER_NAME,PHONE,USER_TYPE) values ('dpem1234','1234','김동식','01022392932','기사');
REM INSERTING into C##DPEM.VEHICLE
SET DEFINE OFF;
Insert into C##DPEM.VEHICLE (CAR_NUM,CAR_TYPE,MAX_WEIGHT,DRIVER_ID) values ('28소8237','카고',5000,'dpem1234');
--------------------------------------------------------
--  DDL for Index PK_DISPATCH
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_DISPATCH" ON "C##DPEM"."DISPATCH" ("DISPATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_ORDER" ON "C##DPEM"."ORDER_SHEET" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SPACE_STATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_SPACE_STATUS" ON "C##DPEM"."SPACE_STATUS" ("CAR_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_USERS" ON "C##DPEM"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_VEHICLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_VEHICLE" ON "C##DPEM"."VEHICLE" ("CAR_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DISPATCH
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_DISPATCH" ON "C##DPEM"."DISPATCH" ("DISPATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_ORDER" ON "C##DPEM"."ORDER_SHEET" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SPACE_STATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_SPACE_STATUS" ON "C##DPEM"."SPACE_STATUS" ("CAR_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_USERS" ON "C##DPEM"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_VEHICLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DPEM"."PK_VEHICLE" ON "C##DPEM"."VEHICLE" ("CAR_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DISPATCH
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."DISPATCH" MODIFY ("DISPATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."DISPATCH" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."DISPATCH" MODIFY ("DRIVER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."DISPATCH" MODIFY ("CAR_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."DISPATCH" MODIFY ("MATCHED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."DISPATCH" ADD CONSTRAINT "PK_DISPATCH" PRIMARY KEY ("DISPATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_SHEET
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("ORIGIN" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("DEST" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("CARGO_INFO" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("PICKUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."ORDER_SHEET" ADD CONSTRAINT "CHK_STATUS" CHECK (status IN ('대기', '배차', '완료')) ENABLE;
  ALTER TABLE "C##DPEM"."ORDER_SHEET" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPACE_STATUS
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."SPACE_STATUS" MODIFY ("CAR_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."SPACE_STATUS" MODIFY ("CURRENT_CAPA" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."SPACE_STATUS" MODIFY ("RETURN_DEST" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."SPACE_STATUS" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."SPACE_STATUS" ADD CONSTRAINT "CHK_CAPA" CHECK (current_capa BETWEEN 0 AND 100) ENABLE;
  ALTER TABLE "C##DPEM"."SPACE_STATUS" ADD CONSTRAINT "PK_SPACE_STATUS" PRIMARY KEY ("CAR_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."USERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."USERS" MODIFY ("USER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."USERS" ADD CONSTRAINT "CHK_USER_TYPE" CHECK (user_type IN ('고객', '기사')) ENABLE;
  ALTER TABLE "C##DPEM"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICLE
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."VEHICLE" MODIFY ("CAR_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."VEHICLE" MODIFY ("CAR_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."VEHICLE" MODIFY ("MAX_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."VEHICLE" MODIFY ("DRIVER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DPEM"."VEHICLE" ADD CONSTRAINT "CHK_WEIGHT" CHECK (max_weight > 0) ENABLE;
  ALTER TABLE "C##DPEM"."VEHICLE" ADD CONSTRAINT "CHK_CAR_TYPE" CHECK (car_type IN ('카고', '윙바디', '탑차', '냉동탑차', '다마스', '라보', '기타')) ENABLE;
  ALTER TABLE "C##DPEM"."VEHICLE" ADD CONSTRAINT "PK_VEHICLE" PRIMARY KEY ("CAR_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPATCH
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."DISPATCH" ADD CONSTRAINT "FK_DISPATCH_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "C##DPEM"."ORDER_SHEET" ("ORDER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##DPEM"."DISPATCH" ADD CONSTRAINT "FK_DISPATCH_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "C##DPEM"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##DPEM"."DISPATCH" ADD CONSTRAINT "FK_DISPATCH_CAR" FOREIGN KEY ("CAR_NUM")
	  REFERENCES "C##DPEM"."VEHICLE" ("CAR_NUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_SHEET
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."ORDER_SHEET" ADD CONSTRAINT "FK_ORDER_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##DPEM"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPACE_STATUS
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."SPACE_STATUS" ADD CONSTRAINT "FK_SPACE_CAR" FOREIGN KEY ("CAR_NUM")
	  REFERENCES "C##DPEM"."VEHICLE" ("CAR_NUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICLE
--------------------------------------------------------

  ALTER TABLE "C##DPEM"."VEHICLE" ADD CONSTRAINT "FK_VEHICLE_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "C##DPEM"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
